### ISSUE TITLE
How to link is not working

### ISSUE THREAD

**Issue by niketnaik** [kishorkurian123/Wkhtmltopdf-PHP-CodeIgniter#1]
The link I have written a simple how to here : http://repulsor.me/installing-wkhtmltopdf-and-using-wkhtmltopdf-in-codeigniter/
 you have provided is seems to be expired.  Is there any change you can reset the link?

**Comment by kishorkurian123** [comment]
The link is down, and I dont think I can get it up anytime soon. If you are still in need, kindly check the link in Waybackmachine.

That might help.
